# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: eclipse-envio-indexer
networks:
  - id: 84532
    start_block: 33388105
    rpc: https://sepolia.base.org
    contracts:
      - name: ProductPaymentService
        address:
          - 0x9d0948391f7e84fcac40b8e792a406ac7c4d591f
        handler: src/EventHandlers.ts
        events:
          - event: PaymentReceived(address indexed payer, uint256 indexed productId, uint256 amount)
          - event: ProductAdded(uint256 indexed productId, uint256 price, address indexed creator, string contentId, bool mustBeVerified)
          - event: ProductUpdated(uint256 indexed productId, uint256 newPrice)
field_selection:
  transaction_fields:
    - 'hash'
    - 'transactionIndex'
unordered_multichain_mode: true
preload_handlers: true
